//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workforce
{
    using System;
    using System.Collections.Generic;
    
    public partial class wf_emp
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public string Resume { get; set; }
        public Nullable<int> Employeeid { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Position { get; set; }
        public string Experience { get; set; }
        public string Password { get; set; }
        public string Tokan { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
    }
}
